export const SAVE_FORECAST_DATA = "SAVE_FORECAST_DATA";
export const REMOVE_LOCATION_DATA = "REMOVE_LOCATION_DATA";

export const SAVE_LOCATION = "SAVE_LOCATION";
export const REMOVE_LOCATION = "REMOVE_LOCATION";
