export const SAVE_FORECAST_DATA = "SAVE_FORECAST_DATA";
export const REMOVE_LOCATION_DATA = "REMOVE_LOCATION_DATA";

export const SAVE_LOCATION = "SAVE_LOCATION";
export const REMOVE_LOCATION = "REMOVE_LOCATION";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION"

export const RESET_STORE = "RESET_STORE";

export const AUTOMATIC_UPDATES = "AUTOMATIC_UPDATES";